name: tuxagent
version: '0.1.0'
summary: AI desktop assistant for Linux
description: |
  TuxAgent is a friendly AI assistant for Linux desktop users.
  Ask questions, attach screenshots, get help with your system.

  Features:
  - Screenshot analysis with vision AI
  - 50+ system tools (files, network, processes)
  - Native GTK4 interface
  - CLI support

  "I know what I want to do, just not how to do it on Linux" — TuxAgent helps with that.

grade: stable
base: core22
confinement: classic

architectures:
  - build-on: amd64

apps:
  tuxagent:
    command: bin/tuxagent-wrapper
    desktop: share/applications/org.tuxagent.desktop

  tux:
    command: bin/tux-wrapper

  daemon:
    command: bin/tuxagent-daemon-wrapper
    daemon: simple

parts:
  tuxagent:
    plugin: nil
    source: .
    build-packages:
      - python3-pip
    stage-packages:
      - python3
      - python3-pip
      - python3-gi
      - python3-gi-cairo
      - python3-dbus
      - gir1.2-gtk-4.0
      - gir1.2-adw-1
      - libgtk-4-1
      - libadwaita-1-0
    override-build: |
      craftctl default

      # Copy source files
      mkdir -p $CRAFT_PART_INSTALL/opt/tuxagent
      cp -r src $CRAFT_PART_INSTALL/opt/tuxagent/
      cp -r config $CRAFT_PART_INSTALL/opt/tuxagent/

      # Install Python dependencies to snap's lib
      pip3 install --target=$CRAFT_PART_INSTALL/opt/tuxagent/lib \
        httpx Pillow markdown psutil python-dateutil requests \
        beautifulsoup4 distro PyPDF2 python-docx openpyxl chardet dnspython aiohttp

      # Create directories
      mkdir -p $CRAFT_PART_INSTALL/bin
      mkdir -p $CRAFT_PART_INSTALL/share/applications
      mkdir -p $CRAFT_PART_INSTALL/share/icons/hicolor/256x256/apps

      # Create GUI wrapper script
      printf '%s\n' \
        '#!/bin/bash' \
        'export PYTHONPATH="$SNAP/opt/tuxagent/lib:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH"' \
        'export GI_TYPELIB_PATH="$SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0:$GI_TYPELIB_PATH"' \
        'exec python3 "$SNAP/opt/tuxagent/src/ui/main.py" "$@"' \
        > $CRAFT_PART_INSTALL/bin/tuxagent-wrapper
      chmod +x $CRAFT_PART_INSTALL/bin/tuxagent-wrapper

      # Create CLI wrapper script
      printf '%s\n' \
        '#!/bin/bash' \
        'export PYTHONPATH="$SNAP/opt/tuxagent/lib:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH"' \
        'exec python3 "$SNAP/opt/tuxagent/src/cli/tux.py" "$@"' \
        > $CRAFT_PART_INSTALL/bin/tux-wrapper
      chmod +x $CRAFT_PART_INSTALL/bin/tux-wrapper

      # Create daemon wrapper script
      printf '%s\n' \
        '#!/bin/bash' \
        'export PYTHONPATH="$SNAP/opt/tuxagent/lib:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH"' \
        'export GI_TYPELIB_PATH="$SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0:$GI_TYPELIB_PATH"' \
        'exec python3 "$SNAP/opt/tuxagent/src/daemon/main.py" "$@"' \
        > $CRAFT_PART_INSTALL/bin/tuxagent-daemon-wrapper
      chmod +x $CRAFT_PART_INSTALL/bin/tuxagent-daemon-wrapper

      # Copy desktop file and icon
      cp data/org.tuxagent.desktop $CRAFT_PART_INSTALL/share/applications/
      cp data/icons/hicolor/256x256/apps/tuxagent.png $CRAFT_PART_INSTALL/share/icons/hicolor/256x256/apps/
